<?php
use AppBundle\Entity\User;
use AppBundle\Entity\UserExtern;

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

  public function findByMail($email){
    $query = $this->execRequest("SELECT * FROM users  WHERE email= :email ",array('email'=> $email));
    if( $query->rowCount() == 1 ){
      $query->setFetchMode(PDO::FETCH_CLASS,'User');
    $user=$query->fetch();
    return $user;
    }
    else {
        return false;
    }
      }
}
